### ISSUE TITLE
Empty date ranges are not found to be empty

### ISSUE THREAD

**Issue by jabrythehutt** [Rescla/range-ts#23]
`NumberRange.closedOpen(new Date(0), new Date(0)).isEmpty()` is returning `false`

I suspect this is down to `new Date(0) === new Date(0)` being `false`, perhaps this should be done using `.valueOf()`?

**Comment by Rescla** [comment]
Yeah, I agree. I overlooked the fact that valueOf is not implicitly used for equals checks. So equals checks between endpoints should use valueOf in `number-range.ts`

It may also be useful to support Dates in toString, either using valueOf also or perhaps toISOString if it's available?

The workaround for this is to call valueOf when creating new NumberRanges, but it would be nicer to support it properly.

**Comment by Rescla** [comment]
Should be fixed in 0.1.7, let me know if it works for you.

**Comment by jabrythehutt** [comment]
Thanks @Rescla it's now working as expected!
